version: "3.8"

services:
  frontend:
    image: bhavukm/fe-swarm
    ports:
      - "80:80"
    networks:
      - webnet
    deploy:
      placement:
        constraints:
          - node.role == worker    

  backend:
    image: bhavukm/be2
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.role == worker    

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - webnet
    deploy:
      placement:
        constraints:
          - node.role == worker

networks:
  webnet:

volumes:
  dbdata:
